name: money_flow
description: A personal finance app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # SQLite
  sqflite: ^2.3.0
  sqflite_common: ^2.5.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.0

  # Gráficos
  fl_chart: ^0.63.0

  # Calendario
  table_calendar: ^3.0.9

  # Gestión de estado
  get: ^4.6.5

  # Fechas
  intl: ^0.18.1

  # Iconos
  font_awesome_flutter: ^10.5.0

  # Preferencias
  shared_preferences: ^2.2.1

  # Exportación de datos
  csv: ^5.0.2
  pdf: ^3.10.4
  printing: ^5.11.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/