name: money_flow
description: A personal finance app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # SQLite
  sqflite: ^2.3.0
  sqflite_common: ^2.5.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.0

  # Gráficos
  fl_chart: ^0.63.0

  # Calendario
  table_calendar: ^3.0.9

  # Gestión de estado
  get: ^4.6.5

  # Fechas
  intl: ^0.18.1

  # Iconos
  font_awesome_flutter: ^10.5.0

  # Preferencias
  shared_preferences: ^2.2.1

  # Exportación de datos
  csv: ^5.0.2
  pdf: ^3.10.4
  printing: ^5.11.1
  url_launcher: ^6.2.1
  file_selector: ^0.9.2+1  # Para seleccionar archivos

  # Info de la app
  package_info_plus: ^8.0.0

  # Notificaciones
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2  # Para manejar zonas horarias
  permission_handler: ^11.3.1  # Para solicitar permisos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lib/l10n/locales/es.json
    - lib/l10n/locales/en.json

flutter_launcher_icons:
  remove_alpha_ios: true
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#2563EB"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"